{"name": "test_div[负数相除]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.5 == 2", "trace": "self = <test_calc_new.TestCalc object at 0x7f12719d4c70>, get_calc = <pythoncode.calculator.Calculator object at 0x7f12719d4670>\nget_div_datas = [-1, -2, 2]\n\n    @pytest.mark.run(order=4)\n    # 测试div函数\n    def test_div(self, get_calc, get_div_datas):\n        try:\n            # 调用div函数，返回的结果保存在result里面\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result,2)\n        except Exception as e:\n            print(e)\n        #判断result结果是否等于期望的值\n>       assert result == get_div_datas[2]\nE       assert 0.5 == 2\n\ntest_calc_new.py:33: AssertionError"}, "attachments": [{"name": "stdout", "source": "0c56e2f0-14d8-49ac-ae8c-c57a89b910a6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_div_datas", "value": "[-1, -2, 2]"}], "start": 1609518820558, "stop": 1609518820559, "uuid": "167e26b8-8a32-4fe4-a960-0a107c2fc6fd", "historyId": "62f7aba48a198147c2f1ed8b0199e361", "testCaseId": "b433a02ec13245ef6dd3b014f7c89e96", "fullName": "pytestwork2.test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "pytestwork2"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "ygl-virtual-machine"}, {"name": "thread", "value": "17277-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytestwork2.test_calc_new"}]}